### ISSUE TITLE
Using MAMP

### ISSUE THREAD

**Issue by macbruker** [darrenmothersele/stylex-barebones#1]
I'm exploring your stylex-barebones example and I like the simplicity.

I'm testing out replacing the PHP build in server with MAMP, and I see that the `/about` page doesn't load. Am I trying something not yet possible or is there a way to use MAMP?

**Comment by darrenmothersele** [comment]
It probably needs a .htaccess rewrite rule to ensure all requests go to index.php

This might help (Stylex is based on Silex) - https://gist.github.com/crzapata/3390080

**Comment by macbruker** [comment]
Ok, I'll try to figure it out :)

**Comment by macbruker** [comment]
Creating a `.htaccess` file like this worked.

```
<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On
    #RewriteBase /path/to/app
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>
```

I'm not sure what do do with the second part of the gist you linked to, but maybe i don't need it?

```
$app->get('/your_mamp_htdocs_silex_app_root/', function() {
    return 'Hello World!';
});
```
