### ISSUE TITLE
Duplicate post in sample project

### ISSUE THREAD

**Issue by macbruker** [darrenmothersele/stylex-barebones#2]
When running the project locally the front page returns two posts, but there is only one post in `content/articles`. If I create another post, this is how it is listed on the frontpage.
- My First Post
- My First Post
- My Second Post
- My Second Post

**Comment by davidvandenbor** [comment]
Hi Martin (and Darren :-)

This is how I fixed the duplicate posts problem: by removing the duplicate posts from the array in **templates/index.html**

``` twig
<html>
  <head>
    <title>Hello!</title>
  </head>
  <body>

    {% include 'components/menu.html' %}

    {% block content %}
      <h1>Hello World!</h1>

      {% set newArray = [] %}
      {% for post in content.articles %}

        {% if post not in newArray %}
        {% include 'components/teaser.html' with post %}
        {% set newArray = newArray|merge([post]) %}
        {% endif %}

      {% endfor %}

    {% endblock %}

  </body>
</html>
```

Cheers, David!

**Comment by davidvandenbor** [comment]
Hi, with David again!

I see the problem now: Darren forgot to delete line 55 in **src/Stylex/Application.php**
So the update wasn't reflected in the composer download:

``` twig
     $content[basename(dirname($file->getPathname()))][$file->getBasename('.md')] = &$data; 
     $content[basename(dirname($file->getPathname()))][$file->getBasename('.md')] = $data; 
```

If you delete the first line (line 55) you don't have to apply my fix :-)

**Comment by darrenmothersele** [comment]
Thanks @David-van-den-Bor 

If you update Stylex, you should see this in `src/Stylex/Application.json`


        $content[basename(dirname($file->getPathname()))][] = $data; 
        $content[basename(dirname($file->getPathname()))][$file->getBasename('.md')] = $data; 

This is so that the articles are available via array keys, and by name.
